//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GojaSudaRooms.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketProd
    {
        public int IdUser { get; set; }
        public int IdProduct { get; set; }
        public int IdBasket { get; set; }
        public Nullable<int> Count { get; set; }
        public byte[] PhotoProduct { get; set; }
        public string Material { get; set; }
        public string NameProduct { get; set; }
        public string Description { get; set; }
        public string NameCategory { get; set; }
        public int IdCategory { get; set; }
        public decimal Price { get; set; }
    }
}
