//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GojaSudaRooms.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderManager
    {
        public int IdUser { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> NumOrder { get; set; }
        public System.DateTime Date { get; set; }
        public int IdBasket { get; set; }
        public int IdOrder { get; set; }
        public string NameCategory { get; set; }
        public Nullable<int> Count { get; set; }
        public decimal Price { get; set; }
        public string NameProduct { get; set; }
    }
}
