//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GojaSudaRooms.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrderView
    {
        public int IdOrder { get; set; }
        public int IdBasket { get; set; }
        public System.DateTime Date { get; set; }
        public int IdProduct { get; set; }
        public int IdCategory { get; set; }
        public decimal Price { get; set; }
        public byte[] PhotoProduct { get; set; }
        public string Material { get; set; }
        public string Description { get; set; }
        public string NameProduct { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int UIDUser { get; set; }
        public string Patronymic { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int BIDBasket { get; set; }
        public int OIDOrder { get; set; }
        public int BIDProduct { get; set; }
        public int IdUser { get; set; }
        public decimal Bprice { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
